services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV_MODE=${DEV_MODE-false}
    container_name: video-processor-backend
    ports:
      - "5001:5001"
    volumes:
      - ./temp:/app/temp
      - ./input:/app/input
      - ./output:/app/output
      # Dev mode: mount source for hot reload
      - ./:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - PYTHONUNBUFFERED=1
      - MAX_CONTENT_LENGTH=2147483648  # 2GB in bytes
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5001/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - video-processor-network
    profiles: ["dev", "prod"]
    # Dev mode: override command for hot reload
    command: ${BACKEND_CMD:-python app.py}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - DEV_MODE=true
    container_name: video-processor-frontend
    ports:
      - "3005:3005"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=/api
      - NODE_ENV=${NODE_ENV:-development}
      - CHOKIDAR_USEPOLLING=true
      - PORT=3005
      - DEV_MODE=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - video-processor-network
    profiles: ["dev", "prod"]
    # Dev mode: override command for hot reload
    command: ${FRONTEND_CMD:-npm start}

  # Legacy CLI version (optional)
  video-processor-cli:
    build: .
    container_name: video-processor-cli
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python main.py
    stdin_open: true
    tty: true
    profiles:
      - cli

  # Batch processing version (optional)
  video-processor-batch:
    build: .
    container_name: video-processor-batch
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - INPUT_FILE=${INPUT_FILE:-input/sample.mp4}
      - OUTPUT_FILE=${OUTPUT_FILE:-output/processed.mp4}
      - TARGET_RATIO_W=${TARGET_RATIO_W:-9}
      - TARGET_RATIO_H=${TARGET_RATIO_H:-16}
      - RESIZE_METHOD=${RESIZE_METHOD:-crop}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python batch_process.py
    profiles:
      - batch

volumes:
  frontend_node_modules:
  temp_data:
  input_data:
  output_data:

networks:
  video-processor-network:
    driver: bridge

# Usage:
#   docker-compose --profile dev up   # for hot reload/dev
#   docker-compose --profile prod up  # for production